services:
  postgres:
    image: postgres
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
    ports:
        - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
    - 5431:80

volumes:
  postgres-data:
